'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ChevronDown, Heart, ListPlus, Pause, Play, Repeat, Shuffle, SkipBack, SkipForward } from 'lucide-react';
import { usePlayerStore } from '../../lib/player-store';
import { supabase } from '../../lib/supabase';
const lyrics = ['ตัวอย่างเนื้อเพลง', 'เลือกเพลงจากคลังเพื่อดูเนื้อเพลงของคุณ', 'เนื้อเพลงจะแสดงและเลื่อนตามจังหวะเพลง', 'คุณสามารถเลื่อนดูเนื้อหาได้ตามต้องการ'];
export default function PlayerPage() {
  const track=usePlayerStore(s=>s.currentTrack), isPlaying=usePlayerStore(s=>s.isPlaying), isShuffle=usePlayerStore(s=>s.isShuffle), repeatMode=usePlayerStore(s=>s.repeatMode), currentTime=usePlayerStore(s=>s.currentTime), duration=usePlayerStore(s=>s.duration);
  const [displayTrack,setDisplayTrack]=useState(track); const [loadedLyrics,setLoadedLyrics]=useState<string[]>([]);
  useEffect(()=>{let active=true; if(!track)return; setDisplayTrack(track); if(!supabase)return; supabase.from('tracks').select('id,title,artist,cover_url,lrc_url').eq('id',track.id).maybeSingle().then(async({data})=>{if(!active||!data)return; const fresh={...track,title:data.title,artist:data.artist,coverUrl:data.cover_url??track.coverUrl,lrcUrl:data.lrc_url??track.lrcUrl}; setDisplayTrack(fresh); if(fresh.lrcUrl){const response=await fetch(fresh.lrcUrl); if(response.ok){const text=await response.text(); const lines=text.split(/\r?\n/).flatMap(line=>[...line.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\](.*)/g)].map(match=>`${match[1]}:${match[2]} ${match[3].trim()}`)); if(active)setLoadedLyrics(lines.filter(Boolean));}}}); return()=>{active=false};},[track]);
  const liked=usePlayerStore(s=>Boolean(track&&s.likedIds.includes(track.id))), togglePlay=usePlayerStore(s=>s.togglePlay), next=usePlayerStore(s=>s.next), previous=usePlayerStore(s=>s.previous), seek=usePlayerStore(s=>s.seek), toggleShuffle=usePlayerStore(s=>s.toggleShuffle), cycleRepeat=usePlayerStore(s=>s.cycleRepeat), toggleLike=usePlayerStore(s=>s.toggleLike), addToQueue=usePlayerStore(s=>s.addToQueue);
  const time=(v:number)=>`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`;
  if(!track)return <main className="full-player bg-gradient-to-br from-violet-700 to-slate-950"><div className="player-backdrop"/><header className="full-player-header"><Link href="/" aria-label="กลับหน้าหลัก"><ChevronDown size={28}/></Link><span>กำลังเล่น</span><span/></header><section className="player-empty"><div className="player-empty-cover">♪</div><h1>ยังไม่ได้เลือกเพลง</h1><p>เลือกเพลงจากหน้าหลักหรือคลังเพลงก่อน</p><Link className="primary-button" href="/">กลับไปเลือกเพลง</Link></section></main>;
  return <main className={`full-player bg-gradient-to-br ${displayTrack?.color??track.color??'from-violet-700 to-slate-950'}`}><div className="player-backdrop"/><header className="full-player-header"><Link href="/" aria-label="ปิดหน้าเล่นเพลง"><ChevronDown size={28}/></Link><span>กำลังเล่น</span><button type="button" aria-label="ตัวเลือก">•••</button></header><section className="player-main"><div className={`large-cover ${displayTrack?.coverUrl?'has-image':''}`}>{displayTrack?.coverUrl?<img src={displayTrack.coverUrl} alt={`ปก ${displayTrack.title}`}/>: '♪'}</div><div className="full-track-meta"><div><h1>{displayTrack?.title??track.title}</h1><p>{displayTrack?.artist??track.artist}</p></div><button type="button" className={liked?'liked':''} onClick={()=>toggleLike(track.id)} aria-label="เพลงที่ชอบ"><Heart size={24} fill={liked?'currentColor':'none'}/></button></div><input className="full-progress" type="range" min="0" max={duration||.1} value={Math.min(currentTime,duration||.1)} step=".1" onChange={e=>seek(Number(e.target.value))} aria-label="ตำแหน่งเพลง"/><div className="time-row"><span>{time(currentTime)}</span><span>{time(duration)}</span></div><div className="full-controls"><button type="button" className={isShuffle?'active-control':''} onClick={toggleShuffle}><Shuffle size={22}/></button><button type="button" onClick={previous}><SkipBack size={30}/></button><button type="button" className="full-play" onClick={togglePlay} aria-label={isPlaying?'หยุดเพลง':'เล่นเพลง'}>{isPlaying?<Pause size={30}/>:<Play size={30}/>}</button><button type="button" onClick={next}><SkipForward size={30}/></button><button type="button" className={repeatMode!=='off'?'active-control':''} onClick={cycleRepeat}><Repeat size={22}/></button></div><div className="player-extra"><button type="button" onClick={()=>addToQueue(track)}><ListPlus size={21}/>เพิ่มเข้าคิว</button><Link href="/library">เปิดคลังเพลง</Link></div><div className="lyrics-panel"><h2>เนื้อเพลง</h2>{lyrics.map((line,i)=><p className={i===0?'lyrics-active':''} key={line}>{line}</p>)}</div></section></main>;
}



