'use client';

import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BarChart3, ExternalLink, ListMusic, Settings, UploadCloud } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import './admin.css';

export default function AdminPage() {
  const [tracks, setTracks] = useState<{ id: string; title: string; artist: string; created_at: string }[]>([]); const [siteName, setSiteName] = useState('MySpotify'); const [savedName, setSavedName] = useState('');
  useEffect(() => { const saved = window.localStorage.getItem('myspotify-site-name'); if (saved) { setSiteName(saved); setSavedName(saved); } if (supabase) supabase.from('tracks').select('id,title,artist,created_at').order('created_at', { ascending: false }).then(({ data }) => setTracks(data ?? [])); }, []);
  const saveSettings = (e: FormEvent) => { e.preventDefault(); window.localStorage.setItem('myspotify-site-name', siteName.trim() || 'MySpotify'); setSavedName(siteName.trim() || 'MySpotify'); };
  const [audio, setAudio] = useState<File | null>(null); const [cover, setCover] = useState<File | null>(null); const [lrc, setLrc] = useState<File | null>(null); const [title, setTitle] = useState(''); const [artist, setArtist] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const pick = (setter: (file: File | null) => void) => (e: ChangeEvent<HTMLInputElement>) => setter(e.target.files?.[0] || null);
  async function submit(e: FormEvent) { e.preventDefault(); const client = supabase; if (!client || !audio || !title || !artist) { setMessage('กรุณาตั้งค่า Supabase และกรอกข้อมูลให้ครบ'); return; } setBusy(true); setMessage('กำลังอัปโหลด...'); try { const id = crypto.randomUUID(); const upload = async (bucket: string, file: File, ext: string) => { const path = `${id}.${ext}`; const result = await client.storage.from(bucket).upload(path, file, { upsert: true }); if (result.error) throw result.error; return client.storage.from(bucket).getPublicUrl(path).data.publicUrl; }; const url = await upload('audio', audio, 'mp3'); const cover_url = cover ? await upload('covers', cover, cover.name.split('.').pop() || 'jpg') : null; const lrc_url = lrc ? await upload('lyrics', lrc, 'lrc') : null; const result = await client.from('tracks').insert({ id, title, artist, url, cover_url, lrc_url }); if (result.error) throw result.error; setMessage('อัปโหลดสำเร็จแล้ว'); setTitle(''); setArtist(''); setAudio(null); setCover(null); setLrc(null); } catch (error) { setMessage(error instanceof Error ? error.message : 'อัปโหลดไม่สำเร็จ'); } finally { setBusy(false); } }
  return <main className="admin-page"><Link href="/" className="back-link"><ArrowLeft size={17}/>กลับหน้าหลัก</Link><div className="admin-shell"><header className="admin-top"><div><p className="eyebrow">ADMIN DASHBOARD</p><h1>{savedName || 'MySpotify'}</h1><p>จัดการคลังเพลงและการตั้งค่าเว็บ</p></div><div className="admin-actions"><Link href="/" className="admin-outline"><ExternalLink size={15}/>ดูหน้าเว็บ</Link><Link href="/library" className="admin-outline"><ListMusic size={15}/>คลังเพลง</Link></div></header><div className="stats-grid"><div className="stat-card"><BarChart3 size={20}/><strong>{tracks.length}</strong><span>เพลงทั้งหมด</span></div><div className="stat-card"><ListMusic size={20}/><strong>{tracks.filter((track) => track.artist).length}</strong><span>รายการที่มีศิลปิน</span></div><div className="stat-card"><UploadCloud size={20}/><strong>MP3</strong><span>รูปแบบที่รองรับ</span></div></div><div className="admin-columns"><div className="admin-card"><div className="admin-heading"><UploadCloud size={25}/><div><p className="eyebrow">Library management</p><h1>เพิ่มเพลงเข้าคลัง</h1></div></div><form onSubmit={submit}><label>ชื่อเพลง<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="ชื่อเพลง"/></label><label>ศิลปิน<input value={artist} onChange={(e)=>setArtist(e.target.value)} placeholder="ชื่อศิลปิน"/></label><label>ไฟล์ MP3<input type="file" accept="audio/mpeg,.mp3" onChange={pick(setAudio)}/></label><label>รูปปก <span className="optional">(ไม่บังคับ)</span><input type="file" accept="image/*" onChange={pick(setCover)}/></label><label>เนื้อเพลง LRC <span className="optional">(ไม่บังคับ)</span><input type="file" accept=".lrc,text/plain" onChange={pick(setLrc)}/></label><button className="primary-button" disabled={busy}>{busy?'กำลังอัปโหลด...':'อัปโหลดเพลง'}</button>{message&&<p className="form-message">{message}</p>}</form></div><div className="admin-card admin-list"><div className="admin-heading"><ListMusic size={25}/><div><p className="eyebrow">YOUR LIBRARY</p><h2>เพลงในคลัง</h2></div></div>{tracks.length ? tracks.map((track) => <div className="admin-track" key={track.id}><span>♪</span><div><strong>{track.title}</strong><small>{track.artist}</small></div></div>) : <p className="form-message">ยังไม่มีเพลงในคลัง</p>}<div className="settings-box"><div className="admin-heading"><Settings size={20}/><h2>ตั้งค่าเว็บ</h2></div><form onSubmit={saveSettings}><label>ชื่อเว็บไซต์<input value={siteName} onChange={(e) => setSiteName(e.target.value)} /></label><button className="primary-button">บันทึกชื่อเว็บ</button></form></div></div></div></div></main>;
}



