'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Clipboard, Home, Library, Play, Search, Youtube } from 'lucide-react';

type Result={id:{videoId:string};snippet:{title:string;channelTitle:string;thumbnails:{medium:{url:string}}}};
function extractVideoId(value:string){const text=value.trim().replace(/^['"]|['"]$/g,'');try{const url=new URL(text);const host=url.hostname.replace(/^www\.|^m\.|^music\./,'');if(host==='youtu.be')return url.pathname.split('/').filter(Boolean)[0]?.slice(0,11)||'';if(host.endsWith('youtube.com')){const id=url.searchParams.get('v');if(id)return id.slice(0,11);const parts=url.pathname.split('/').filter(Boolean);const index=parts.findIndex(part=>part==='shorts'||part==='embed'||part==='live');if(index>=0&&parts[index+1])return parts[index+1].slice(0,11);}}catch{}const match=text.match(/(?:v=|youtu\.be\/|youtube\.com\/(?:shorts\/|embed\/|live\/))([A-Za-z0-9_-]{11})/);return match?.[1]||'';}

export default function YouTubePage(){
  const [query,setQuery]=useState('');const [results,setResults]=useState<Result[]>([]);const [selected,setSelected]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const playLink=()=>{const id=extractVideoId(query);if(!id){setSelected('');setMessage('ลิงก์ไม่ถูกต้อง ลองวางลิงก์ YouTube แบบ youtube.com/watch?v=... หรือ youtu.be/...');return;}setSelected(id);setMessage('พร้อมเล่นเพลงแล้ว');};
  const search=async(e:FormEvent)=>{e.preventDefault();const linkId=extractVideoId(query);if(linkId){playLink();return;}const key=process.env.NEXT_PUBLIC_YOUTUBE_API_KEY;if(!key){setMessage('การค้นหาด้วยชื่อเพลงต้องตั้งค่า YouTube API Key แต่สามารถวางลิงก์แล้วกด “เล่นจากลิงก์” ได้ทันที');return;}if(!query.trim())return;setBusy(true);setMessage('กำลังค้นหา...');try{const response=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=12&q=${encodeURIComponent(query.trim())}&key=${key}`);const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'ค้นหาไม่สำเร็จ');setResults(data.items||[]);setMessage(`พบ ${data.items?.length||0} รายการ`);}catch(error){setMessage(error instanceof Error?error.message:'ค้นหาไม่สำเร็จ');}finally{setBusy(false);}};
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><img src="/Phumtify/phumtify-logo.png" alt=""/></span><span>Phumtify</span></div><nav className="nav-group"><Link className="nav-link" href="/"><Home size={20}/>หน้าหลัก</Link><Link className="nav-link active" href="/youtube"><Youtube size={20}/>YouTube</Link><Link className="nav-link" href="/library"><Library size={20}/>คลังเพลง</Link><Link className="nav-link" href="/player"><Play size={20}/>กำลังเล่น</Link></nav></aside><main className="content-area"><section className="content-scroll youtube-page"><p className="eyebrow">YOUTUBE PLAYER</p><h1 className="page-title">เปิดเพลงจาก YouTube</h1><p className="hero-copy">วางลิงก์แล้วเล่นใน Phumtify ได้ทันที หรือค้นหาด้วยชื่อเพลงเมื่อใส่ API Key แล้ว</p><div className="youtube-search"><Clipboard size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')playLink();}} placeholder="วางลิงก์ YouTube ที่นี่"/><button type="button" className="primary-button" onClick={playLink}>เล่นจากลิงก์</button></div><form className="youtube-search youtube-search-secondary" onSubmit={search}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="หรือค้นหาชื่อเพลง / ศิลปิน"/><button className="primary-button" disabled={busy}>{busy?'กำลังค้นหา...':'ค้นหา'}</button></form>{message&&<p className="form-message">{message}</p>}{selected&&<section className="youtube-player"><iframe src={`https://www.youtube.com/embed/${selected}?autoplay=1&rel=0`} title="YouTube player" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></section>}<div className="youtube-results">{results.map(item=><button type="button" className="youtube-result" key={item.id.videoId} onClick={()=>{setSelected(item.id.videoId);setMessage('พร้อมเล่นเพลงแล้ว')}}><img src={item.snippet.thumbnails.medium.url} alt=""/><span><strong>{item.snippet.title}</strong><small>{item.snippet.channelTitle}</small></span><Play size={18}/></button>)}</div></section></main></div>;
}
