'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Home, Library, Play, Search, Youtube } from 'lucide-react';
type Result={id:{videoId:string};snippet:{title:string;channelTitle:string;thumbnails:{medium:{url:string}}}};
const getVideoId=(value:string)=>{try{const url=new URL(value);return url.hostname.includes('youtu.be')?url.pathname.slice(1):url.searchParams.get('v')||'';}catch{return value.trim();}};
export default function YouTubePage(){
 const [query,setQuery]=useState(''); const [results,setResults]=useState<Result[]>([]); const [selected,setSelected]=useState(''); const [message,setMessage]=useState('');
 const search=async(e:FormEvent)=>{e.preventDefault(); if(!query.trim())return; const key=process.env.NEXT_PUBLIC_YOUTUBE_API_KEY; if(!key){const id=getVideoId(query); if(id){setSelected(id);setMessage('กำลังเล่นลิงก์ YouTube ที่วางไว้');}else setMessage('ต้องตั้งค่า YouTube API Key เพื่อค้นหา หรือวางลิงก์ YouTube โดยตรง');return;} setMessage('กำลังค้นหา...'); const response=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=12&q=${encodeURIComponent(query)}&key=${key}`); const data=await response.json(); if(!response.ok){setMessage(data.error?.message||'ค้นหาไม่สำเร็จ');return;} setResults(data.items||[]); setMessage(`${data.items?.length||0} รายการ`);};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><img src="/Phumtify/phumtify-logo.png" alt=""/></span><span>Phumtify</span></div><nav className="nav-group"><Link className="nav-link" href="/"><Home size={20}/>หน้าหลัก</Link><Link className="nav-link active" href="/youtube"><Youtube size={20}/>ค้นหา YouTube</Link><Link className="nav-link" href="/library"><Library size={20}/>คลังเพลง</Link><Link className="nav-link" href="/player"><Play size={20}/>กำลังเล่น</Link></nav></aside><main className="content-area"><section className="content-scroll youtube-page"><p className="eyebrow">YOUTUBE DISCOVERY</p><h1 className="page-title">ค้นหาเพลงจาก YouTube</h1><p className="hero-copy">เล่นผ่าน YouTube Player ใน Phumtify โดยไม่ดาวน์โหลดไฟล์เสียง</p><form className="youtube-search" onSubmit={search}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อเพลง ศิลปิน หรือวางลิงก์ YouTube"/><button className="primary-button">ค้นหา</button></form>{message&&<p className="form-message">{message}</p>}{selected&&<section className="youtube-player"><iframe src={`https://www.youtube.com/embed/${selected}?autoplay=1`} title="YouTube player" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></section>}<div className="youtube-results">{results.map(item=><button type="button" className="youtube-result" key={item.id.videoId} onClick={()=>setSelected(item.id.videoId)}><img src={item.snippet.thumbnails.medium.url} alt=""/><span><strong>{item.snippet.title}</strong><small>{item.snippet.channelTitle}</small></span><Play size={18}/></button>)}</div></section></main></div>;
}
