import { create } from 'zustand';

export type RepeatMode = 'off' | 'all' | 'one';
export type Track = { id: string; title: string; artist: string; album?: string; url: string; coverUrl?: string; lrcUrl?: string; duration?: number; color?: string };

type PlayerState = {
  currentTrack: Track | null; queue: Track[]; queueIndex: number; isPlaying: boolean; volume: number; isShuffle: boolean; repeatMode: RepeatMode; currentTime: number; duration: number; playCounts: Record<string, number>; recentIds: string[]; likedIds: string[];
  playTrack: (track: Track, queue?: Track[]) => void; togglePlay: () => void; setPlaying: (value: boolean) => void; next: () => void; previous: () => void; seek: (time: number) => void; setVolume: (value: number) => void; toggleShuffle: () => void; cycleRepeat: () => void; setProgress: (time: number, duration: number) => void; toggleLike: (trackId: string) => void; playNext: (track: Track) => void; addToQueue: (track: Track) => void; removeFromQueue: (trackId: string) => void;
};

const smartOrder = (items: Track[], counts: Record<string, number>, recent: string[]) => [...items].sort((a, b) => { const score = (t: Track) => (counts[t.id] ?? 0) * 3 - recent.indexOf(t.id) * -0.35 + Math.random() * 4; return score(b) - score(a); });

export const usePlayerStore = create<PlayerState>((set, get) => ({
  currentTrack: null, queue: [], queueIndex: -1, isPlaying: false, volume: 0.8, isShuffle: false, repeatMode: 'off', currentTime: 0, duration: 0, playCounts: {}, recentIds: [], likedIds: [],
  playTrack: (track, queue = [track]) => { const state = get(); const base = queue.length ? queue : [track]; const list = state.isShuffle ? [track, ...smartOrder(base.filter((item) => item.id !== track.id), state.playCounts, state.recentIds)] : base; set({ currentTrack: track, queue: list, queueIndex: 0, isPlaying: true, currentTime: 0, playCounts: { ...state.playCounts, [track.id]: (state.playCounts[track.id] ?? 0) + 1 }, recentIds: [track.id, ...state.recentIds.filter((id) => id !== track.id)].slice(0, 5) }); },
  togglePlay: () => set((state) => ({ isPlaying: !state.isPlaying })), setPlaying: (value) => set({ isPlaying: value }),
  next: () => set((state) => { if (!state.queue.length) return state; const nextIndex = state.queueIndex + 1; if (nextIndex >= state.queue.length && state.repeatMode === 'off') return { ...state, isPlaying: false }; const index = nextIndex >= state.queue.length ? 0 : nextIndex; const track = state.queue[index]; return { ...state, queueIndex: index, currentTrack: track, isPlaying: true, currentTime: 0, playCounts: { ...state.playCounts, [track.id]: (state.playCounts[track.id] ?? 0) + 1 }, recentIds: [track.id, ...state.recentIds.filter((id) => id !== track.id)].slice(0, 5) }; }),
  previous: () => set((state) => { if (!state.queue.length) return state; const index = state.queueIndex <= 0 ? state.queue.length - 1 : state.queueIndex - 1; return { ...state, queueIndex: index, currentTrack: state.queue[index], isPlaying: true, currentTime: 0 }; }),
  seek: (time) => set({ currentTime: time }), setVolume: (value) => set({ volume: Math.max(0, Math.min(1, value)) }), toggleShuffle: () => set((state) => { const enabled = !state.isShuffle; if (!enabled || !state.currentTrack) return { isShuffle: enabled }; const list = [state.currentTrack, ...smartOrder(state.queue.filter((t) => t.id !== state.currentTrack?.id), state.playCounts, state.recentIds)]; return { isShuffle: true, queue: list, queueIndex: 0 }; }), cycleRepeat: () => set((state) => ({ repeatMode: state.repeatMode === 'off' ? 'all' : state.repeatMode === 'all' ? 'one' : 'off' })), setProgress: (currentTime, duration) => set({ currentTime, duration }), toggleLike: (trackId) => set((state) => ({ likedIds: state.likedIds.includes(trackId) ? state.likedIds.filter((id) => id !== trackId) : [...state.likedIds, trackId] })), playNext: (track) => set((state) => { const without = state.queue.filter((item) => item.id !== track.id); const insertAt = state.currentTrack ? Math.min(state.queueIndex + 1, without.length) : 0; return { queue: [...without.slice(0, insertAt), track, ...without.slice(insertAt)], queueIndex: state.currentTrack ? state.queueIndex : 0 }; }), addToQueue: (track) => set((state) => ({ queue: state.queue.some((item) => item.id === track.id) ? state.queue : [...state.queue, track] })), removeFromQueue: (trackId) => set((state) => { const queue = state.queue.filter((item) => item.id !== trackId); const index = Math.min(state.queueIndex, Math.max(0, queue.length - 1)); return { queue, queueIndex: index }; }),
}));

